"""The numbers behind the figures, as a table.

A figure shows a shape; a report also has to state the values, their spread and
how many runs produced them. Without that a reader cannot tell a 4.6x effect
measured once from a 1.4x effect measured nine times, and cannot check a claim
against the axis.

Spread is min-max rather than a standard deviation, for the reason given in
metrics.aggregate: repetition counts here are small enough that a standard
deviation is not meaningful but the observed range is. Cells that were never
run print as "-" rather than 0, so a gap in the matrix stays visible as a gap.
"""
from .io import discover
from .metrics import aggregate

# (column header, aggregator, format). Every column is a metric a reviewer is
# likely to ask for, so the table stands alone without the figures.
COLUMNS = (
    ("commit%", aggregate.commit_rate, "{:.0f}"),
    ("fallback%", aggregate.fallback_rate, "{:.0f}"),
    ("quorum", aggregate.quorum, "{:.0f}"),
    ("cleared", aggregate.cleared, "{:.1f}"),
    ("thru veh/s", aggregate.throughput, "{:.3f}"),
    ("wait s", aggregate.clearance_wait, "{:.2f}"),
    ("stop->dec s", aggregate.stop_to_decision, "{:.2f}"),
    # The retired proposer-only sampling, printed for one cycle so every claim
    # that moves is auditable against the column it moved from.
    ("stop->dec (old)", aggregate.stop_to_decision_proposer, "{:.2f}"),
    ("order lat s", aggregate.bft_latency, "{:.3f}"),
    ("cert lat s", aggregate.cert_latency, "{:.3f}"),
    ("msgs/veh", aggregate.msgs_per_vehicle, "{:.0f}"),
    ("KB/veh", lambda r: _kb(aggregate.bytes_per_vehicle(r)), "{:.1f}"),
    # Not a result: how much of the log had to be thrown away. A cell with a
    # large count here has fewer samples behind every other column in its row.
    ("bad lines", aggregate.corrupt_lines, "{:.0f}"),
)


def _kb(stat):
    """Bytes stat rescaled to KB, keeping the spread consistent."""
    if stat.mean is None:
        return stat
    return aggregate.Stat(stat.mean / 1024, stat.lo / 1024, stat.hi / 1024, stat.n)


def _cell(stat, fmt):
    """mean [min-max] for a measured cell, or "-" when nothing was recorded."""
    if stat.mean is None:
        return "-"
    body = fmt.format(stat.mean)
    if stat.lo is not None and stat.hi is not None and stat.hi - stat.lo > 1e-9:
        body += f" [{fmt.format(stat.lo)}-{fmt.format(stat.hi)}]"
    return body


def rows(runs):
    """One row per (study, arm, k, n) cell, in a stable reading order."""
    out = []
    for key in sorted(runs, key=lambda c: (c[0], str(c[1]), c[3] or 0, c[2] or -1)):
        study, arm, k, n = key
        recs = runs[key]
        cells = [_cell(agg(recs), fmt) for _, agg, fmt in COLUMNS]
        out.append([f"ab{study}", arm, "-" if n is None else str(n),
                    "-" if k is None else str(k), str(len(recs))] + cells)
    return out


def render(runs) -> str:
    header = ["study", "arm", "N", "k", "reps"] + [c[0] for c in COLUMNS]
    table = [header] + rows(runs)
    widths = [max(len(r[i]) for r in table) for i in range(len(header))]
    lines = [
        "| " + " | ".join(h.ljust(w) for h, w in zip(header, widths)) + " |",
        "|" + "|".join("-" * (w + 2) for w in widths) + "|",
    ]
    lines += ["| " + " | ".join(c.ljust(w) for c, w in zip(row, widths)) + " |"
              for row in table[1:]]
    return "\n".join(lines)


def build(results_dir, out_path) -> int:
    runs = discover.load_runs(results_dir)
    if not runs:
        return 0
    text = ("# Ablation results\n\n"
            "Generated by `python3 -m plotter summary`. Values are the mean "
            "across repetitions, with the observed min-max range in brackets "
            "where runs differed. `-` means the cell was never run.\n\n"
            + render(runs) + "\n")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text)
    return len(runs)
