/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bftsmart_communication_V2V_V2VNativeBridge */

#ifndef _Included_bftsmart_communication_V2V_V2VNativeBridge
#define _Included_bftsmart_communication_V2V_V2VNativeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bftsmart_communication_V2V_V2VNativeBridge
 * Method:    nativeInit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_bftsmart_communication_V2V_V2VNativeBridge_nativeInit
  (JNIEnv *, jobject, jint);

/*
 * Class:     bftsmart_communication_V2V_V2VNativeBridge
 * Method:    nativeSendMessage
 * Signature: (II[B)Z
 */
JNIEXPORT jboolean JNICALL Java_bftsmart_communication_V2V_V2VNativeBridge_nativeSendMessage
  (JNIEnv *, jobject, jint, jint, jbyteArray);

/*
 * Class:     bftsmart_communication_V2V_V2VNativeBridge
 * Method:    nativeShutdown
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_bftsmart_communication_V2V_V2VNativeBridge_nativeShutdown
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
