/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bftsmart_demo_intersection_IntersectionServer */

#ifndef _Included_bftsmart_demo_intersection_IntersectionServer
#define _Included_bftsmart_demo_intersection_IntersectionServer
#ifdef __cplusplus
extern "C" {
#endif
#undef bftsmart_demo_intersection_IntersectionServer_BATCH_SIZE
#define bftsmart_demo_intersection_IntersectionServer_BATCH_SIZE 4L
#undef bftsmart_demo_intersection_IntersectionServer_CROSSING_TIME_SECONDS
#define bftsmart_demo_intersection_IntersectionServer_CROSSING_TIME_SECONDS 5L
/*
 * Class:     bftsmart_demo_intersection_IntersectionServer
 * Method:    notifyVehicleCanGo
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_bftsmart_demo_intersection_IntersectionServer_notifyVehicleCanGo
  (JNIEnv *, jobject, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
