#!/usr/bin/env python3
"""Generate the reviewed Phase 2 actual-movement conflict table.

The table is derived only from the already-approved mixed-route manifest and
SUMO internal connection-lane geometry.  It is consumed by runtime metrology;
it never changes the executor's kSafe table.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

from audit_ksafe_geometry import load_movements, load_paths, paths_intersect


APPROACHES = ("N", "S", "E", "W")
DIRECTIONS = ("S", "L", "R")
MOVEMENTS = tuple((approach, direction) for approach in APPROACHES for direction in DIRECTIONS)


def parse_args() -> argparse.Namespace:
    here = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--net", type=Path, default=here / "bft_intersection.net.xml")
    parser.add_argument("--manifest", type=Path, default=here / "phase2_mixed_route_manifest.csv")
    parser.add_argument("--csv-out", type=Path, default=here / "phase2_movement_conflicts.csv")
    parser.add_argument(
        "--header-out",
        type=Path,
        default=here.parent / "veins-veins-5.3.1/src/veins/modules/mobility/traci/Phase2MovementConflicts.h",
    )
    return parser.parse_args()


def movement_name(movement: tuple[str, str]) -> str:
    return f"{movement[0]}-{movement[1]}"


def build_table(net: Path, manifest: Path):
    routes = load_movements(manifest)
    if set(routes) != set(MOVEMENTS):
        missing = sorted(set(MOVEMENTS) - set(routes))
        extra = sorted(set(routes) - set(MOVEMENTS))
        raise ValueError(f"manifest movement mismatch: missing={missing} extra={extra}")
    paths, via_lanes = load_paths(net, routes)
    table: list[list[bool]] = []
    rows = []
    for movement_a in MOVEMENTS:
        table_row = []
        for movement_b in MOVEMENTS:
            same_approach = movement_a[0] == movement_b[0]
            intersects = paths_intersect(paths[movement_a], paths[movement_b])
            conflict = same_approach or intersects
            table_row.append(conflict)
            rows.append({
                "movement_a": movement_name(movement_a),
                "ingress_a": routes[movement_a][0],
                "egress_a": routes[movement_a][1],
                "via_lanes_a": ";".join(via_lanes[movement_a]),
                "movement_b": movement_name(movement_b),
                "ingress_b": routes[movement_b][0],
                "egress_b": routes[movement_b][1],
                "via_lanes_b": ";".join(via_lanes[movement_b]),
                "same_approach": int(same_approach),
                "centerlines_intersect": int(intersects),
                "conflict": int(conflict),
                "rule": "same_approach" if same_approach else "path_intersection" if intersects else "disjoint_paths",
            })
        table.append(table_row)
    return routes, table, rows


def render_header(routes, table) -> str:
    names = ", ".join(f'"{movement_name(movement)}"' for movement in MOVEMENTS)
    ingresses = ", ".join(f'"{routes[movement][0]}"' for movement in MOVEMENTS)
    egresses = ", ".join(f'"{routes[movement][1]}"' for movement in MOVEMENTS)
    matrix = "\n".join(
        "    {" + ", ".join("true" if value else "false" for value in row) + "},"
        for row in table
    )
    return f"""// Generated by fourway/generate_phase2_movement_conflicts.py.  Do not edit.
#pragma once

#include <array>
#include <string_view>

namespace veins::phase2_metrology {{

inline constexpr std::size_t kMovementCount = 12;
inline constexpr std::array<std::string_view, kMovementCount> kMovementNames = {{{names}}};
inline constexpr std::array<std::string_view, kMovementCount> kIngressEdges = {{{ingresses}}};
inline constexpr std::array<std::string_view, kMovementCount> kEgressEdges = {{{egresses}}};
inline constexpr bool kMovementConflicts[kMovementCount][kMovementCount] = {{
{matrix}
}};

}}  // namespace veins::phase2_metrology
"""


def main() -> int:
    args = parse_args()
    routes, table, rows = build_table(args.net, args.manifest)
    if table != [list(row) for row in zip(*table)]:
        raise ValueError("generated conflict table is not symmetric")
    if any(not table[i][i] for i in range(len(table))):
        raise ValueError("movement table diagonal must conflict with itself")

    args.csv_out.parent.mkdir(parents=True, exist_ok=True)
    with args.csv_out.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    args.header_out.parent.mkdir(parents=True, exist_ok=True)
    args.header_out.write_text(render_header(routes, table))
    conflict_cells = sum(sum(row) for row in table)
    print(f"Generated 12x12 table: conflict_cells={conflict_cells} safe_cells={144-conflict_cells}")
    print(f"CSV:    {args.csv_out}")
    print(f"Header: {args.header_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
