// Generated by fourway/generate_phase2_movement_conflicts.py.  Do not edit.
#pragma once

#include <array>
#include <string_view>

namespace veins::phase2_metrology {

inline constexpr std::size_t kMovementCount = 12;
inline constexpr std::array<std::string_view, kMovementCount> kMovementNames = {"N-S", "N-L", "N-R", "S-S", "S-L", "S-R", "E-S", "E-L", "E-R", "W-S", "W-L", "W-R"};
inline constexpr std::array<std::string_view, kMovementCount> kIngressEdges = {"N2C", "N2C", "N2C", "S2C", "S2C", "S2C", "E2C", "E2C", "E2C", "W2C", "W2C", "W2C"};
inline constexpr std::array<std::string_view, kMovementCount> kEgressEdges = {"C2S", "C2E", "C2W", "C2N", "C2W", "C2E", "C2W", "C2S", "C2N", "C2E", "C2N", "C2S"};
inline constexpr bool kMovementConflicts[kMovementCount][kMovementCount] = {
    {true, true, true, false, true, false, true, true, false, true, true, true},
    {true, true, true, true, false, true, true, true, false, true, true, false},
    {true, true, true, false, true, false, true, false, false, false, false, false},
    {false, true, false, true, true, true, true, true, true, true, true, false},
    {true, false, true, true, true, true, true, true, false, true, true, false},
    {false, true, false, true, true, true, false, false, false, true, false, false},
    {true, true, true, true, true, false, true, true, true, false, true, false},
    {true, true, false, true, true, false, true, true, true, true, false, true},
    {false, false, false, true, false, false, true, true, true, false, true, false},
    {true, true, false, true, true, true, false, true, false, true, true, true},
    {true, true, false, true, true, false, true, false, true, true, true, true},
    {true, false, false, false, false, false, false, true, false, true, true, true},
};

}  // namespace veins::phase2_metrology
