// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: bft/bft.proto

package bftconsensus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BFTElectionStatus int32

const (
	BFTElectionStatus_BFT_INIT_CANDIDATE BFTElectionStatus = 0
	BFTElectionStatus_BFT_FIN_CANDIDATE  BFTElectionStatus = 1
	BFTElectionStatus_BFT_FOLLOWER       BFTElectionStatus = 2
	BFTElectionStatus_BFT_LEADER         BFTElectionStatus = 3
)

// Enum value maps for BFTElectionStatus.
var (
	BFTElectionStatus_name = map[int32]string{
		0: "BFT_INIT_CANDIDATE",
		1: "BFT_FIN_CANDIDATE",
		2: "BFT_FOLLOWER",
		3: "BFT_LEADER",
	}
	BFTElectionStatus_value = map[string]int32{
		"BFT_INIT_CANDIDATE": 0,
		"BFT_FIN_CANDIDATE":  1,
		"BFT_FOLLOWER":       2,
		"BFT_LEADER":         3,
	}
)

func (x BFTElectionStatus) Enum() *BFTElectionStatus {
	p := new(BFTElectionStatus)
	*p = x
	return p
}

func (x BFTElectionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BFTElectionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_bft_bft_proto_enumTypes[0].Descriptor()
}

func (BFTElectionStatus) Type() protoreflect.EnumType {
	return &file_bft_bft_proto_enumTypes[0]
}

func (x BFTElectionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BFTElectionStatus.Descriptor instead.
func (BFTElectionStatus) EnumDescriptor() ([]byte, []int) {
	return file_bft_bft_proto_rawDescGZIP(), []int{0}
}

// Phases for attestation/QC
type Phase int32

const (
	Phase_PHASE_UNSPECIFIED Phase = 0
	Phase_PHASE1_VOTE       Phase = 1
	Phase_PHASE2_LEADER     Phase = 2
)

// Enum value maps for Phase.
var (
	Phase_name = map[int32]string{
		0: "PHASE_UNSPECIFIED",
		1: "PHASE1_VOTE",
		2: "PHASE2_LEADER",
	}
	Phase_value = map[string]int32{
		"PHASE_UNSPECIFIED": 0,
		"PHASE1_VOTE":       1,
		"PHASE2_LEADER":     2,
	}
)

func (x Phase) Enum() *Phase {
	p := new(Phase)
	*p = x
	return p
}

func (x Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_bft_bft_proto_enumTypes[1].Descriptor()
}

func (Phase) Type() protoreflect.EnumType {
	return &file_bft_bft_proto_enumTypes[1]
}

func (x Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Phase.Descriptor instead.
func (Phase) EnumDescriptor() ([]byte, []int) {
	return file_bft_bft_proto_rawDescGZIP(), []int{1}
}

type BFTVehicleMeta struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Plate          string                 `protobuf:"bytes,2,opt,name=plate,proto3" json:"plate,omitempty"`
	Direction      string                 `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"` // "N-left", "E-straight", ...
	Status         BFTElectionStatus      `protobuf:"varint,4,opt,name=status,proto3,enum=bftconsensus.BFTElectionStatus" json:"status,omitempty"`
	SentVotes      uint32                 `protobuf:"varint,5,opt,name=sent_votes,json=sentVotes,proto3" json:"sent_votes,omitempty"`                  // optional for debugging/metrics
	ReceivedVotes  uint32                 `protobuf:"varint,6,opt,name=received_votes,json=receivedVotes,proto3" json:"received_votes,omitempty"`      // optional for debugging/metrics
	ElectionTimeMs int64                  `protobuf:"varint,7,opt,name=election_time_ms,json=electionTimeMs,proto3" json:"election_time_ms,omitempty"` // first-ACK (or support) time
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BFTVehicleMeta) Reset() {
	*x = BFTVehicleMeta{}
	mi := &file_bft_bft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BFTVehicleMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BFTVehicleMeta) ProtoMessage() {}

func (x *BFTVehicleMeta) ProtoReflect() protoreflect.Message {
	mi := &file_bft_bft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BFTVehicleMeta.ProtoReflect.Descriptor instead.
func (*BFTVehicleMeta) Descriptor() ([]byte, []int) {
	return file_bft_bft_proto_rawDescGZIP(), []int{0}
}

func (x *BFTVehicleMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BFTVehicleMeta) GetPlate() string {
	if x != nil {
		return x.Plate
	}
	return ""
}

func (x *BFTVehicleMeta) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *BFTVehicleMeta) GetStatus() BFTElectionStatus {
	if x != nil {
		return x.Status
	}
	return BFTElectionStatus_BFT_INIT_CANDIDATE
}

func (x *BFTVehicleMeta) GetSentVotes() uint32 {
	if x != nil {
		return x.SentVotes
	}
	return 0
}

func (x *BFTVehicleMeta) GetReceivedVotes() uint32 {
	if x != nil {
		return x.ReceivedVotes
	}
	return 0
}

func (x *BFTVehicleMeta) GetElectionTimeMs() int64 {
	if x != nil {
		return x.ElectionTimeMs
	}
	return 0
}

// A single signer’s attestation (signature over canonical tuple)
type Attestation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          uint64                 `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`                                 // epoch/term
	Phase         Phase                  `protobuf:"varint,2,opt,name=phase,proto3,enum=bftconsensus.Phase" json:"phase,omitempty"`       // PHASE1_VOTE or PHASE2_LEADER
	SubjectId     string                 `protobuf:"bytes,3,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`       // candidate being supported
	PayloadHash   []byte                 `protobuf:"bytes,4,opt,name=payload_hash,json=payloadHash,proto3" json:"payload_hash,omitempty"` // H( payload )
	SignerId      string                 `protobuf:"bytes,5,opt,name=signer_id,json=signerId,proto3" json:"signer_id,omitempty"`          // who signed
	Sig           []byte                 `protobuf:"bytes,6,opt,name=sig,proto3" json:"sig,omitempty"`                                    // ed25519 signature over canonical bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attestation) Reset() {
	*x = Attestation{}
	mi := &file_bft_bft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attestation) ProtoMessage() {}

func (x *Attestation) ProtoReflect() protoreflect.Message {
	mi := &file_bft_bft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attestation.ProtoReflect.Descriptor instead.
func (*Attestation) Descriptor() ([]byte, []int) {
	return file_bft_bft_proto_rawDescGZIP(), []int{1}
}

func (x *Attestation) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *Attestation) GetPhase() Phase {
	if x != nil {
		return x.Phase
	}
	return Phase_PHASE_UNSPECIFIED
}

func (x *Attestation) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *Attestation) GetPayloadHash() []byte {
	if x != nil {
		return x.PayloadHash
	}
	return nil
}

func (x *Attestation) GetSignerId() string {
	if x != nil {
		return x.SignerId
	}
	return ""
}

func (x *Attestation) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

// A quorum certificate = ≥ 2f+1 attestations over SAME (view,phase,subject,payload_hash)
type QuorumCert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          uint64                 `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Phase         Phase                  `protobuf:"varint,2,opt,name=phase,proto3,enum=bftconsensus.Phase" json:"phase,omitempty"`
	SubjectId     string                 `protobuf:"bytes,3,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	PayloadHash   []byte                 `protobuf:"bytes,4,opt,name=payload_hash,json=payloadHash,proto3" json:"payload_hash,omitempty"`
	Sigs          []*Attestation         `protobuf:"bytes,5,rep,name=sigs,proto3" json:"sigs,omitempty"` // distinct signer_id; size >= 2f+1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuorumCert) Reset() {
	*x = QuorumCert{}
	mi := &file_bft_bft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuorumCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuorumCert) ProtoMessage() {}

func (x *QuorumCert) ProtoReflect() protoreflect.Message {
	mi := &file_bft_bft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuorumCert.ProtoReflect.Descriptor instead.
func (*QuorumCert) Descriptor() ([]byte, []int) {
	return file_bft_bft_proto_rawDescGZIP(), []int{2}
}

func (x *QuorumCert) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *QuorumCert) GetPhase() Phase {
	if x != nil {
		return x.Phase
	}
	return Phase_PHASE_UNSPECIFIED
}

func (x *QuorumCert) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *QuorumCert) GetPayloadHash() []byte {
	if x != nil {
		return x.PayloadHash
	}
	return nil
}

func (x *QuorumCert) GetSigs() []*Attestation {
	if x != nil {
		return x.Sigs
	}
	return nil
}

// SEND: carries full payload (meta); signed by sender
type SendVote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          uint64                 `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	SubjectId     string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"` // candidate id
	Payload       *BFTVehicleMeta        `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                      // meta(subject)
	SenderAtt     *Attestation           `protobuf:"bytes,4,opt,name=sender_att,json=senderAtt,proto3" json:"sender_att,omitempty"` // signature over (view, PHASE1_VOTE, subject_id, H(payload), signer=sender_id)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendVote) Reset() {
	*x = SendVote{}
	mi := &file_bft_bft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVote) ProtoMessage() {}

func (x *SendVote) ProtoReflect() protoreflect.Message {
	mi := &file_bft_bft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVote.ProtoReflect.Descriptor instead.
func (*SendVote) Descriptor() ([]byte, []int) {
	return file_bft_bft_proto_rawDescGZIP(), []int{3}
}

func (x *SendVote) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *SendVote) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *SendVote) GetPayload() *BFTVehicleMeta {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SendVote) GetSenderAtt() *Attestation {
	if x != nil {
		return x.SenderAtt
	}
	return nil
}

// ECHO/READY: carry only the payload hash + signer’s attestation
type EchoVote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          uint64                 `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	SubjectId     string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	PayloadHash   []byte                 `protobuf:"bytes,3,opt,name=payload_hash,json=payloadHash,proto3" json:"payload_hash,omitempty"`
	Att           *Attestation           `protobuf:"bytes,4,opt,name=att,proto3" json:"att,omitempty"` // signer’s ECHO attestation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoVote) Reset() {
	*x = EchoVote{}
	mi := &file_bft_bft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoVote) ProtoMessage() {}

func (x *EchoVote) ProtoReflect() protoreflect.Message {
	mi := &file_bft_bft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoVote.ProtoReflect.Descriptor instead.
func (*EchoVote) Descriptor() ([]byte, []int) {
	return file_bft_bft_proto_rawDescGZIP(), []int{4}
}

func (x *EchoVote) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *EchoVote) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *EchoVote) GetPayloadHash() []byte {
	if x != nil {
		return x.PayloadHash
	}
	return nil
}

func (x *EchoVote) GetAtt() *Attestation {
	if x != nil {
		return x.Att
	}
	return nil
}

type ReadyVote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          uint64                 `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	SubjectId     string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	PayloadHash   []byte                 `protobuf:"bytes,3,opt,name=payload_hash,json=payloadHash,proto3" json:"payload_hash,omitempty"`
	Att           *Attestation           `protobuf:"bytes,4,opt,name=att,proto3" json:"att,omitempty"` // signer’s READY attestation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyVote) Reset() {
	*x = ReadyVote{}
	mi := &file_bft_bft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyVote) ProtoMessage() {}

func (x *ReadyVote) ProtoReflect() protoreflect.Message {
	mi := &file_bft_bft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyVote.ProtoReflect.Descriptor instead.
func (*ReadyVote) Descriptor() ([]byte, []int) {
	return file_bft_bft_proto_rawDescGZIP(), []int{5}
}

func (x *ReadyVote) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *ReadyVote) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *ReadyVote) GetPayloadHash() []byte {
	if x != nil {
		return x.PayloadHash
	}
	return nil
}

func (x *ReadyVote) GetAtt() *Attestation {
	if x != nil {
		return x.Att
	}
	return nil
}

// SEND: carries {meta(subject), QC1}
type SendLeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          uint64                 `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	SubjectId     string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	FinMeta       *BFTVehicleMeta        `protobuf:"bytes,3,opt,name=fin_meta,json=finMeta,proto3" json:"fin_meta,omitempty"`       // meta(subject)
	Qc1           *QuorumCert            `protobuf:"bytes,4,opt,name=qc1,proto3" json:"qc1,omitempty"`                              // proof of Phase-1
	SenderAtt     *Attestation           `protobuf:"bytes,5,opt,name=sender_att,json=senderAtt,proto3" json:"sender_att,omitempty"` // signature over (view, PHASE2_LEADER, subject_id, H(fin_meta||qc1), signer=sender_id)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendLeader) Reset() {
	*x = SendLeader{}
	mi := &file_bft_bft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendLeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLeader) ProtoMessage() {}

func (x *SendLeader) ProtoReflect() protoreflect.Message {
	mi := &file_bft_bft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLeader.ProtoReflect.Descriptor instead.
func (*SendLeader) Descriptor() ([]byte, []int) {
	return file_bft_bft_proto_rawDescGZIP(), []int{6}
}

func (x *SendLeader) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *SendLeader) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *SendLeader) GetFinMeta() *BFTVehicleMeta {
	if x != nil {
		return x.FinMeta
	}
	return nil
}

func (x *SendLeader) GetQc1() *QuorumCert {
	if x != nil {
		return x.Qc1
	}
	return nil
}

func (x *SendLeader) GetSenderAtt() *Attestation {
	if x != nil {
		return x.SenderAtt
	}
	return nil
}

type EchoLeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          uint64                 `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	SubjectId     string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	PayloadHash   []byte                 `protobuf:"bytes,3,opt,name=payload_hash,json=payloadHash,proto3" json:"payload_hash,omitempty"` // H(fin_meta||qc1)
	Att           *Attestation           `protobuf:"bytes,4,opt,name=att,proto3" json:"att,omitempty"`                                    // signer’s ECHO attestation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoLeader) Reset() {
	*x = EchoLeader{}
	mi := &file_bft_bft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoLeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoLeader) ProtoMessage() {}

func (x *EchoLeader) ProtoReflect() protoreflect.Message {
	mi := &file_bft_bft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoLeader.ProtoReflect.Descriptor instead.
func (*EchoLeader) Descriptor() ([]byte, []int) {
	return file_bft_bft_proto_rawDescGZIP(), []int{7}
}

func (x *EchoLeader) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *EchoLeader) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *EchoLeader) GetPayloadHash() []byte {
	if x != nil {
		return x.PayloadHash
	}
	return nil
}

func (x *EchoLeader) GetAtt() *Attestation {
	if x != nil {
		return x.Att
	}
	return nil
}

type ReadyLeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          uint64                 `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	SubjectId     string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	PayloadHash   []byte                 `protobuf:"bytes,3,opt,name=payload_hash,json=payloadHash,proto3" json:"payload_hash,omitempty"` // H(fin_meta||qc1)
	Att           *Attestation           `protobuf:"bytes,4,opt,name=att,proto3" json:"att,omitempty"`                                    // signer’s READY attestation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyLeader) Reset() {
	*x = ReadyLeader{}
	mi := &file_bft_bft_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyLeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyLeader) ProtoMessage() {}

func (x *ReadyLeader) ProtoReflect() protoreflect.Message {
	mi := &file_bft_bft_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyLeader.ProtoReflect.Descriptor instead.
func (*ReadyLeader) Descriptor() ([]byte, []int) {
	return file_bft_bft_proto_rawDescGZIP(), []int{8}
}

func (x *ReadyLeader) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *ReadyLeader) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *ReadyLeader) GetPayloadHash() []byte {
	if x != nil {
		return x.PayloadHash
	}
	return nil
}

func (x *ReadyLeader) GetAtt() *Attestation {
	if x != nil {
		return x.Att
	}
	return nil
}

type Wire struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Wire_SendVote
	//	*Wire_EchoVote
	//	*Wire_ReadyVote
	//	*Wire_SendLeader
	//	*Wire_EchoLeader
	//	*Wire_ReadyLeader
	Kind          isWire_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wire) Reset() {
	*x = Wire{}
	mi := &file_bft_bft_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wire) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wire) ProtoMessage() {}

func (x *Wire) ProtoReflect() protoreflect.Message {
	mi := &file_bft_bft_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wire.ProtoReflect.Descriptor instead.
func (*Wire) Descriptor() ([]byte, []int) {
	return file_bft_bft_proto_rawDescGZIP(), []int{9}
}

func (x *Wire) GetKind() isWire_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Wire) GetSendVote() *SendVote {
	if x != nil {
		if x, ok := x.Kind.(*Wire_SendVote); ok {
			return x.SendVote
		}
	}
	return nil
}

func (x *Wire) GetEchoVote() *EchoVote {
	if x != nil {
		if x, ok := x.Kind.(*Wire_EchoVote); ok {
			return x.EchoVote
		}
	}
	return nil
}

func (x *Wire) GetReadyVote() *ReadyVote {
	if x != nil {
		if x, ok := x.Kind.(*Wire_ReadyVote); ok {
			return x.ReadyVote
		}
	}
	return nil
}

func (x *Wire) GetSendLeader() *SendLeader {
	if x != nil {
		if x, ok := x.Kind.(*Wire_SendLeader); ok {
			return x.SendLeader
		}
	}
	return nil
}

func (x *Wire) GetEchoLeader() *EchoLeader {
	if x != nil {
		if x, ok := x.Kind.(*Wire_EchoLeader); ok {
			return x.EchoLeader
		}
	}
	return nil
}

func (x *Wire) GetReadyLeader() *ReadyLeader {
	if x != nil {
		if x, ok := x.Kind.(*Wire_ReadyLeader); ok {
			return x.ReadyLeader
		}
	}
	return nil
}

type isWire_Kind interface {
	isWire_Kind()
}

type Wire_SendVote struct {
	SendVote *SendVote `protobuf:"bytes,1,opt,name=send_vote,json=sendVote,proto3,oneof"`
}

type Wire_EchoVote struct {
	EchoVote *EchoVote `protobuf:"bytes,2,opt,name=echo_vote,json=echoVote,proto3,oneof"`
}

type Wire_ReadyVote struct {
	ReadyVote *ReadyVote `protobuf:"bytes,3,opt,name=ready_vote,json=readyVote,proto3,oneof"`
}

type Wire_SendLeader struct {
	SendLeader *SendLeader `protobuf:"bytes,4,opt,name=send_leader,json=sendLeader,proto3,oneof"`
}

type Wire_EchoLeader struct {
	EchoLeader *EchoLeader `protobuf:"bytes,5,opt,name=echo_leader,json=echoLeader,proto3,oneof"`
}

type Wire_ReadyLeader struct {
	ReadyLeader *ReadyLeader `protobuf:"bytes,6,opt,name=ready_leader,json=readyLeader,proto3,oneof"`
}

func (*Wire_SendVote) isWire_Kind() {}

func (*Wire_EchoVote) isWire_Kind() {}

func (*Wire_ReadyVote) isWire_Kind() {}

func (*Wire_SendLeader) isWire_Kind() {}

func (*Wire_EchoLeader) isWire_Kind() {}

func (*Wire_ReadyLeader) isWire_Kind() {}

type WireAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`        // transport-level ack (not a vote)
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // optional error/debug
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireAck) Reset() {
	*x = WireAck{}
	mi := &file_bft_bft_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireAck) ProtoMessage() {}

func (x *WireAck) ProtoReflect() protoreflect.Message {
	mi := &file_bft_bft_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireAck.ProtoReflect.Descriptor instead.
func (*WireAck) Descriptor() ([]byte, []int) {
	return file_bft_bft_proto_rawDescGZIP(), []int{10}
}

func (x *WireAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *WireAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_bft_bft_proto protoreflect.FileDescriptor

const file_bft_bft_proto_rawDesc = "" +
	"\n" +
	"\rbft/bft.proto\x12\fbftconsensus\"\xfd\x01\n" +
	"\x0eBFTVehicleMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05plate\x18\x02 \x01(\tR\x05plate\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\tR\tdirection\x127\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1f.bftconsensus.BFTElectionStatusR\x06status\x12\x1d\n" +
	"\n" +
	"sent_votes\x18\x05 \x01(\rR\tsentVotes\x12%\n" +
	"\x0ereceived_votes\x18\x06 \x01(\rR\rreceivedVotes\x12(\n" +
	"\x10election_time_ms\x18\a \x01(\x03R\x0eelectionTimeMs\"\xbd\x01\n" +
	"\vAttestation\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x04R\x04view\x12)\n" +
	"\x05phase\x18\x02 \x01(\x0e2\x13.bftconsensus.PhaseR\x05phase\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x03 \x01(\tR\tsubjectId\x12!\n" +
	"\fpayload_hash\x18\x04 \x01(\fR\vpayloadHash\x12\x1b\n" +
	"\tsigner_id\x18\x05 \x01(\tR\bsignerId\x12\x10\n" +
	"\x03sig\x18\x06 \x01(\fR\x03sig\"\xbc\x01\n" +
	"\n" +
	"QuorumCert\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x04R\x04view\x12)\n" +
	"\x05phase\x18\x02 \x01(\x0e2\x13.bftconsensus.PhaseR\x05phase\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x03 \x01(\tR\tsubjectId\x12!\n" +
	"\fpayload_hash\x18\x04 \x01(\fR\vpayloadHash\x12-\n" +
	"\x04sigs\x18\x05 \x03(\v2\x19.bftconsensus.AttestationR\x04sigs\"\xaf\x01\n" +
	"\bSendVote\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x04R\x04view\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x126\n" +
	"\apayload\x18\x03 \x01(\v2\x1c.bftconsensus.BFTVehicleMetaR\apayload\x128\n" +
	"\n" +
	"sender_att\x18\x04 \x01(\v2\x19.bftconsensus.AttestationR\tsenderAtt\"\x8d\x01\n" +
	"\bEchoVote\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x04R\x04view\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12!\n" +
	"\fpayload_hash\x18\x03 \x01(\fR\vpayloadHash\x12+\n" +
	"\x03att\x18\x04 \x01(\v2\x19.bftconsensus.AttestationR\x03att\"\x8e\x01\n" +
	"\tReadyVote\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x04R\x04view\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12!\n" +
	"\fpayload_hash\x18\x03 \x01(\fR\vpayloadHash\x12+\n" +
	"\x03att\x18\x04 \x01(\v2\x19.bftconsensus.AttestationR\x03att\"\xde\x01\n" +
	"\n" +
	"SendLeader\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x04R\x04view\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x127\n" +
	"\bfin_meta\x18\x03 \x01(\v2\x1c.bftconsensus.BFTVehicleMetaR\afinMeta\x12*\n" +
	"\x03qc1\x18\x04 \x01(\v2\x18.bftconsensus.QuorumCertR\x03qc1\x128\n" +
	"\n" +
	"sender_att\x18\x05 \x01(\v2\x19.bftconsensus.AttestationR\tsenderAtt\"\x8f\x01\n" +
	"\n" +
	"EchoLeader\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x04R\x04view\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12!\n" +
	"\fpayload_hash\x18\x03 \x01(\fR\vpayloadHash\x12+\n" +
	"\x03att\x18\x04 \x01(\v2\x19.bftconsensus.AttestationR\x03att\"\x90\x01\n" +
	"\vReadyLeader\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x04R\x04view\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12!\n" +
	"\fpayload_hash\x18\x03 \x01(\fR\vpayloadHash\x12+\n" +
	"\x03att\x18\x04 \x01(\v2\x19.bftconsensus.AttestationR\x03att\"\xf0\x02\n" +
	"\x04Wire\x125\n" +
	"\tsend_vote\x18\x01 \x01(\v2\x16.bftconsensus.SendVoteH\x00R\bsendVote\x125\n" +
	"\techo_vote\x18\x02 \x01(\v2\x16.bftconsensus.EchoVoteH\x00R\bechoVote\x128\n" +
	"\n" +
	"ready_vote\x18\x03 \x01(\v2\x17.bftconsensus.ReadyVoteH\x00R\treadyVote\x12;\n" +
	"\vsend_leader\x18\x04 \x01(\v2\x18.bftconsensus.SendLeaderH\x00R\n" +
	"sendLeader\x12;\n" +
	"\vecho_leader\x18\x05 \x01(\v2\x18.bftconsensus.EchoLeaderH\x00R\n" +
	"echoLeader\x12>\n" +
	"\fready_leader\x18\x06 \x01(\v2\x19.bftconsensus.ReadyLeaderH\x00R\vreadyLeaderB\x06\n" +
	"\x04kind\"1\n" +
	"\aWireAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason*d\n" +
	"\x11BFTElectionStatus\x12\x16\n" +
	"\x12BFT_INIT_CANDIDATE\x10\x00\x12\x15\n" +
	"\x11BFT_FIN_CANDIDATE\x10\x01\x12\x10\n" +
	"\fBFT_FOLLOWER\x10\x02\x12\x0e\n" +
	"\n" +
	"BFT_LEADER\x10\x03*B\n" +
	"\x05Phase\x12\x15\n" +
	"\x11PHASE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vPHASE1_VOTE\x10\x01\x12\x11\n" +
	"\rPHASE2_LEADER\x10\x022G\n" +
	"\fBFTConsensus\x127\n" +
	"\x06Gossip\x12\x12.bftconsensus.Wire\x1a\x15.bftconsensus.WireAck(\x010\x012\xaf\x03\n" +
	"\x11BFTConsensusUnary\x12@\n" +
	"\x0fReceiveSendVote\x12\x16.bftconsensus.SendVote\x1a\x15.bftconsensus.WireAck\x12@\n" +
	"\x0fReceiveEchoVote\x12\x16.bftconsensus.EchoVote\x1a\x15.bftconsensus.WireAck\x12B\n" +
	"\x10ReceiveReadyVote\x12\x17.bftconsensus.ReadyVote\x1a\x15.bftconsensus.WireAck\x12D\n" +
	"\x11ReceiveSendLeader\x12\x18.bftconsensus.SendLeader\x1a\x15.bftconsensus.WireAck\x12D\n" +
	"\x11ReceiveEchoLeader\x12\x18.bftconsensus.EchoLeader\x1a\x15.bftconsensus.WireAck\x12F\n" +
	"\x12ReceiveReadyLeader\x12\x19.bftconsensus.ReadyLeader\x1a\x15.bftconsensus.WireAckBKZIgithub.com/ymalegao/DistributedSystemsforAVs/pb/bftconsensus;bftconsensusb\x06proto3"

var (
	file_bft_bft_proto_rawDescOnce sync.Once
	file_bft_bft_proto_rawDescData []byte
)

func file_bft_bft_proto_rawDescGZIP() []byte {
	file_bft_bft_proto_rawDescOnce.Do(func() {
		file_bft_bft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bft_bft_proto_rawDesc), len(file_bft_bft_proto_rawDesc)))
	})
	return file_bft_bft_proto_rawDescData
}

var file_bft_bft_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_bft_bft_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_bft_bft_proto_goTypes = []any{
	(BFTElectionStatus)(0), // 0: bftconsensus.BFTElectionStatus
	(Phase)(0),             // 1: bftconsensus.Phase
	(*BFTVehicleMeta)(nil), // 2: bftconsensus.BFTVehicleMeta
	(*Attestation)(nil),    // 3: bftconsensus.Attestation
	(*QuorumCert)(nil),     // 4: bftconsensus.QuorumCert
	(*SendVote)(nil),       // 5: bftconsensus.SendVote
	(*EchoVote)(nil),       // 6: bftconsensus.EchoVote
	(*ReadyVote)(nil),      // 7: bftconsensus.ReadyVote
	(*SendLeader)(nil),     // 8: bftconsensus.SendLeader
	(*EchoLeader)(nil),     // 9: bftconsensus.EchoLeader
	(*ReadyLeader)(nil),    // 10: bftconsensus.ReadyLeader
	(*Wire)(nil),           // 11: bftconsensus.Wire
	(*WireAck)(nil),        // 12: bftconsensus.WireAck
}
var file_bft_bft_proto_depIdxs = []int32{
	0,  // 0: bftconsensus.BFTVehicleMeta.status:type_name -> bftconsensus.BFTElectionStatus
	1,  // 1: bftconsensus.Attestation.phase:type_name -> bftconsensus.Phase
	1,  // 2: bftconsensus.QuorumCert.phase:type_name -> bftconsensus.Phase
	3,  // 3: bftconsensus.QuorumCert.sigs:type_name -> bftconsensus.Attestation
	2,  // 4: bftconsensus.SendVote.payload:type_name -> bftconsensus.BFTVehicleMeta
	3,  // 5: bftconsensus.SendVote.sender_att:type_name -> bftconsensus.Attestation
	3,  // 6: bftconsensus.EchoVote.att:type_name -> bftconsensus.Attestation
	3,  // 7: bftconsensus.ReadyVote.att:type_name -> bftconsensus.Attestation
	2,  // 8: bftconsensus.SendLeader.fin_meta:type_name -> bftconsensus.BFTVehicleMeta
	4,  // 9: bftconsensus.SendLeader.qc1:type_name -> bftconsensus.QuorumCert
	3,  // 10: bftconsensus.SendLeader.sender_att:type_name -> bftconsensus.Attestation
	3,  // 11: bftconsensus.EchoLeader.att:type_name -> bftconsensus.Attestation
	3,  // 12: bftconsensus.ReadyLeader.att:type_name -> bftconsensus.Attestation
	5,  // 13: bftconsensus.Wire.send_vote:type_name -> bftconsensus.SendVote
	6,  // 14: bftconsensus.Wire.echo_vote:type_name -> bftconsensus.EchoVote
	7,  // 15: bftconsensus.Wire.ready_vote:type_name -> bftconsensus.ReadyVote
	8,  // 16: bftconsensus.Wire.send_leader:type_name -> bftconsensus.SendLeader
	9,  // 17: bftconsensus.Wire.echo_leader:type_name -> bftconsensus.EchoLeader
	10, // 18: bftconsensus.Wire.ready_leader:type_name -> bftconsensus.ReadyLeader
	11, // 19: bftconsensus.BFTConsensus.Gossip:input_type -> bftconsensus.Wire
	5,  // 20: bftconsensus.BFTConsensusUnary.ReceiveSendVote:input_type -> bftconsensus.SendVote
	6,  // 21: bftconsensus.BFTConsensusUnary.ReceiveEchoVote:input_type -> bftconsensus.EchoVote
	7,  // 22: bftconsensus.BFTConsensusUnary.ReceiveReadyVote:input_type -> bftconsensus.ReadyVote
	8,  // 23: bftconsensus.BFTConsensusUnary.ReceiveSendLeader:input_type -> bftconsensus.SendLeader
	9,  // 24: bftconsensus.BFTConsensusUnary.ReceiveEchoLeader:input_type -> bftconsensus.EchoLeader
	10, // 25: bftconsensus.BFTConsensusUnary.ReceiveReadyLeader:input_type -> bftconsensus.ReadyLeader
	12, // 26: bftconsensus.BFTConsensus.Gossip:output_type -> bftconsensus.WireAck
	12, // 27: bftconsensus.BFTConsensusUnary.ReceiveSendVote:output_type -> bftconsensus.WireAck
	12, // 28: bftconsensus.BFTConsensusUnary.ReceiveEchoVote:output_type -> bftconsensus.WireAck
	12, // 29: bftconsensus.BFTConsensusUnary.ReceiveReadyVote:output_type -> bftconsensus.WireAck
	12, // 30: bftconsensus.BFTConsensusUnary.ReceiveSendLeader:output_type -> bftconsensus.WireAck
	12, // 31: bftconsensus.BFTConsensusUnary.ReceiveEchoLeader:output_type -> bftconsensus.WireAck
	12, // 32: bftconsensus.BFTConsensusUnary.ReceiveReadyLeader:output_type -> bftconsensus.WireAck
	26, // [26:33] is the sub-list for method output_type
	19, // [19:26] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_bft_bft_proto_init() }
func file_bft_bft_proto_init() {
	if File_bft_bft_proto != nil {
		return
	}
	file_bft_bft_proto_msgTypes[9].OneofWrappers = []any{
		(*Wire_SendVote)(nil),
		(*Wire_EchoVote)(nil),
		(*Wire_ReadyVote)(nil),
		(*Wire_SendLeader)(nil),
		(*Wire_EchoLeader)(nil),
		(*Wire_ReadyLeader)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bft_bft_proto_rawDesc), len(file_bft_bft_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_bft_bft_proto_goTypes,
		DependencyIndexes: file_bft_bft_proto_depIdxs,
		EnumInfos:         file_bft_bft_proto_enumTypes,
		MessageInfos:      file_bft_bft_proto_msgTypes,
	}.Build()
	File_bft_bft_proto = out.File
	file_bft_bft_proto_goTypes = nil
	file_bft_bft_proto_depIdxs = nil
}
