// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: bft/bft.proto

package bftconsensus

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BFTConsensus_Gossip_FullMethodName = "/bftconsensus.BFTConsensus/Gossip"
)

// BFTConsensusClient is the client API for BFTConsensus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// One bi-di stream per peer; you push Wire messages, they push acks (optional)
type BFTConsensusClient interface {
	Gossip(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Wire, WireAck], error)
}

type bFTConsensusClient struct {
	cc grpc.ClientConnInterface
}

func NewBFTConsensusClient(cc grpc.ClientConnInterface) BFTConsensusClient {
	return &bFTConsensusClient{cc}
}

func (c *bFTConsensusClient) Gossip(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Wire, WireAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BFTConsensus_ServiceDesc.Streams[0], BFTConsensus_Gossip_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Wire, WireAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BFTConsensus_GossipClient = grpc.BidiStreamingClient[Wire, WireAck]

// BFTConsensusServer is the server API for BFTConsensus service.
// All implementations must embed UnimplementedBFTConsensusServer
// for forward compatibility.
//
// One bi-di stream per peer; you push Wire messages, they push acks (optional)
type BFTConsensusServer interface {
	Gossip(grpc.BidiStreamingServer[Wire, WireAck]) error
	mustEmbedUnimplementedBFTConsensusServer()
}

// UnimplementedBFTConsensusServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBFTConsensusServer struct{}

func (UnimplementedBFTConsensusServer) Gossip(grpc.BidiStreamingServer[Wire, WireAck]) error {
	return status.Errorf(codes.Unimplemented, "method Gossip not implemented")
}
func (UnimplementedBFTConsensusServer) mustEmbedUnimplementedBFTConsensusServer() {}
func (UnimplementedBFTConsensusServer) testEmbeddedByValue()                      {}

// UnsafeBFTConsensusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BFTConsensusServer will
// result in compilation errors.
type UnsafeBFTConsensusServer interface {
	mustEmbedUnimplementedBFTConsensusServer()
}

func RegisterBFTConsensusServer(s grpc.ServiceRegistrar, srv BFTConsensusServer) {
	// If the following call pancis, it indicates UnimplementedBFTConsensusServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BFTConsensus_ServiceDesc, srv)
}

func _BFTConsensus_Gossip_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BFTConsensusServer).Gossip(&grpc.GenericServerStream[Wire, WireAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BFTConsensus_GossipServer = grpc.BidiStreamingServer[Wire, WireAck]

// BFTConsensus_ServiceDesc is the grpc.ServiceDesc for BFTConsensus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BFTConsensus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bftconsensus.BFTConsensus",
	HandlerType: (*BFTConsensusServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Gossip",
			Handler:       _BFTConsensus_Gossip_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "bft/bft.proto",
}

const (
	BFTConsensusUnary_ReceiveSendVote_FullMethodName    = "/bftconsensus.BFTConsensusUnary/ReceiveSendVote"
	BFTConsensusUnary_ReceiveEchoVote_FullMethodName    = "/bftconsensus.BFTConsensusUnary/ReceiveEchoVote"
	BFTConsensusUnary_ReceiveReadyVote_FullMethodName   = "/bftconsensus.BFTConsensusUnary/ReceiveReadyVote"
	BFTConsensusUnary_ReceiveSendLeader_FullMethodName  = "/bftconsensus.BFTConsensusUnary/ReceiveSendLeader"
	BFTConsensusUnary_ReceiveEchoLeader_FullMethodName  = "/bftconsensus.BFTConsensusUnary/ReceiveEchoLeader"
	BFTConsensusUnary_ReceiveReadyLeader_FullMethodName = "/bftconsensus.BFTConsensusUnary/ReceiveReadyLeader"
)

// BFTConsensusUnaryClient is the client API for BFTConsensusUnary service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BFTConsensusUnaryClient interface {
	ReceiveSendVote(ctx context.Context, in *SendVote, opts ...grpc.CallOption) (*WireAck, error)
	ReceiveEchoVote(ctx context.Context, in *EchoVote, opts ...grpc.CallOption) (*WireAck, error)
	ReceiveReadyVote(ctx context.Context, in *ReadyVote, opts ...grpc.CallOption) (*WireAck, error)
	ReceiveSendLeader(ctx context.Context, in *SendLeader, opts ...grpc.CallOption) (*WireAck, error)
	ReceiveEchoLeader(ctx context.Context, in *EchoLeader, opts ...grpc.CallOption) (*WireAck, error)
	ReceiveReadyLeader(ctx context.Context, in *ReadyLeader, opts ...grpc.CallOption) (*WireAck, error)
}

type bFTConsensusUnaryClient struct {
	cc grpc.ClientConnInterface
}

func NewBFTConsensusUnaryClient(cc grpc.ClientConnInterface) BFTConsensusUnaryClient {
	return &bFTConsensusUnaryClient{cc}
}

func (c *bFTConsensusUnaryClient) ReceiveSendVote(ctx context.Context, in *SendVote, opts ...grpc.CallOption) (*WireAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WireAck)
	err := c.cc.Invoke(ctx, BFTConsensusUnary_ReceiveSendVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFTConsensusUnaryClient) ReceiveEchoVote(ctx context.Context, in *EchoVote, opts ...grpc.CallOption) (*WireAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WireAck)
	err := c.cc.Invoke(ctx, BFTConsensusUnary_ReceiveEchoVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFTConsensusUnaryClient) ReceiveReadyVote(ctx context.Context, in *ReadyVote, opts ...grpc.CallOption) (*WireAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WireAck)
	err := c.cc.Invoke(ctx, BFTConsensusUnary_ReceiveReadyVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFTConsensusUnaryClient) ReceiveSendLeader(ctx context.Context, in *SendLeader, opts ...grpc.CallOption) (*WireAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WireAck)
	err := c.cc.Invoke(ctx, BFTConsensusUnary_ReceiveSendLeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFTConsensusUnaryClient) ReceiveEchoLeader(ctx context.Context, in *EchoLeader, opts ...grpc.CallOption) (*WireAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WireAck)
	err := c.cc.Invoke(ctx, BFTConsensusUnary_ReceiveEchoLeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFTConsensusUnaryClient) ReceiveReadyLeader(ctx context.Context, in *ReadyLeader, opts ...grpc.CallOption) (*WireAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WireAck)
	err := c.cc.Invoke(ctx, BFTConsensusUnary_ReceiveReadyLeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BFTConsensusUnaryServer is the server API for BFTConsensusUnary service.
// All implementations must embed UnimplementedBFTConsensusUnaryServer
// for forward compatibility.
type BFTConsensusUnaryServer interface {
	ReceiveSendVote(context.Context, *SendVote) (*WireAck, error)
	ReceiveEchoVote(context.Context, *EchoVote) (*WireAck, error)
	ReceiveReadyVote(context.Context, *ReadyVote) (*WireAck, error)
	ReceiveSendLeader(context.Context, *SendLeader) (*WireAck, error)
	ReceiveEchoLeader(context.Context, *EchoLeader) (*WireAck, error)
	ReceiveReadyLeader(context.Context, *ReadyLeader) (*WireAck, error)
	mustEmbedUnimplementedBFTConsensusUnaryServer()
}

// UnimplementedBFTConsensusUnaryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBFTConsensusUnaryServer struct{}

func (UnimplementedBFTConsensusUnaryServer) ReceiveSendVote(context.Context, *SendVote) (*WireAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveSendVote not implemented")
}
func (UnimplementedBFTConsensusUnaryServer) ReceiveEchoVote(context.Context, *EchoVote) (*WireAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveEchoVote not implemented")
}
func (UnimplementedBFTConsensusUnaryServer) ReceiveReadyVote(context.Context, *ReadyVote) (*WireAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveReadyVote not implemented")
}
func (UnimplementedBFTConsensusUnaryServer) ReceiveSendLeader(context.Context, *SendLeader) (*WireAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveSendLeader not implemented")
}
func (UnimplementedBFTConsensusUnaryServer) ReceiveEchoLeader(context.Context, *EchoLeader) (*WireAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveEchoLeader not implemented")
}
func (UnimplementedBFTConsensusUnaryServer) ReceiveReadyLeader(context.Context, *ReadyLeader) (*WireAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveReadyLeader not implemented")
}
func (UnimplementedBFTConsensusUnaryServer) mustEmbedUnimplementedBFTConsensusUnaryServer() {}
func (UnimplementedBFTConsensusUnaryServer) testEmbeddedByValue()                           {}

// UnsafeBFTConsensusUnaryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BFTConsensusUnaryServer will
// result in compilation errors.
type UnsafeBFTConsensusUnaryServer interface {
	mustEmbedUnimplementedBFTConsensusUnaryServer()
}

func RegisterBFTConsensusUnaryServer(s grpc.ServiceRegistrar, srv BFTConsensusUnaryServer) {
	// If the following call pancis, it indicates UnimplementedBFTConsensusUnaryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BFTConsensusUnary_ServiceDesc, srv)
}

func _BFTConsensusUnary_ReceiveSendVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendVote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFTConsensusUnaryServer).ReceiveSendVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFTConsensusUnary_ReceiveSendVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFTConsensusUnaryServer).ReceiveSendVote(ctx, req.(*SendVote))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFTConsensusUnary_ReceiveEchoVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoVote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFTConsensusUnaryServer).ReceiveEchoVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFTConsensusUnary_ReceiveEchoVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFTConsensusUnaryServer).ReceiveEchoVote(ctx, req.(*EchoVote))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFTConsensusUnary_ReceiveReadyVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadyVote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFTConsensusUnaryServer).ReceiveReadyVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFTConsensusUnary_ReceiveReadyVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFTConsensusUnaryServer).ReceiveReadyVote(ctx, req.(*ReadyVote))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFTConsensusUnary_ReceiveSendLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendLeader)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFTConsensusUnaryServer).ReceiveSendLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFTConsensusUnary_ReceiveSendLeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFTConsensusUnaryServer).ReceiveSendLeader(ctx, req.(*SendLeader))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFTConsensusUnary_ReceiveEchoLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoLeader)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFTConsensusUnaryServer).ReceiveEchoLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFTConsensusUnary_ReceiveEchoLeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFTConsensusUnaryServer).ReceiveEchoLeader(ctx, req.(*EchoLeader))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFTConsensusUnary_ReceiveReadyLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadyLeader)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFTConsensusUnaryServer).ReceiveReadyLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFTConsensusUnary_ReceiveReadyLeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFTConsensusUnaryServer).ReceiveReadyLeader(ctx, req.(*ReadyLeader))
	}
	return interceptor(ctx, in, info, handler)
}

// BFTConsensusUnary_ServiceDesc is the grpc.ServiceDesc for BFTConsensusUnary service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BFTConsensusUnary_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bftconsensus.BFTConsensusUnary",
	HandlerType: (*BFTConsensusUnaryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveSendVote",
			Handler:    _BFTConsensusUnary_ReceiveSendVote_Handler,
		},
		{
			MethodName: "ReceiveEchoVote",
			Handler:    _BFTConsensusUnary_ReceiveEchoVote_Handler,
		},
		{
			MethodName: "ReceiveReadyVote",
			Handler:    _BFTConsensusUnary_ReceiveReadyVote_Handler,
		},
		{
			MethodName: "ReceiveSendLeader",
			Handler:    _BFTConsensusUnary_ReceiveSendLeader_Handler,
		},
		{
			MethodName: "ReceiveEchoLeader",
			Handler:    _BFTConsensusUnary_ReceiveEchoLeader_Handler,
		},
		{
			MethodName: "ReceiveReadyLeader",
			Handler:    _BFTConsensusUnary_ReceiveReadyLeader_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bft/bft.proto",
}
