// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: pb/intersection.proto

package consensus

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IntersectionConsensus_CandidateVote_FullMethodName  = "/consensus.IntersectionConsensus/CandidateVote"
	IntersectionConsensus_LeaderElection_FullMethodName = "/consensus.IntersectionConsensus/LeaderElection"
)

// IntersectionConsensusClient is the client API for IntersectionConsensus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IntersectionConsensusClient interface {
	CandidateVote(ctx context.Context, in *CandidateVoteRequest, opts ...grpc.CallOption) (*CandidateVoteResponse, error)
	LeaderElection(ctx context.Context, in *LeaderElectionRequest, opts ...grpc.CallOption) (*LeaderElectionResponse, error)
}

type intersectionConsensusClient struct {
	cc grpc.ClientConnInterface
}

func NewIntersectionConsensusClient(cc grpc.ClientConnInterface) IntersectionConsensusClient {
	return &intersectionConsensusClient{cc}
}

func (c *intersectionConsensusClient) CandidateVote(ctx context.Context, in *CandidateVoteRequest, opts ...grpc.CallOption) (*CandidateVoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CandidateVoteResponse)
	err := c.cc.Invoke(ctx, IntersectionConsensus_CandidateVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intersectionConsensusClient) LeaderElection(ctx context.Context, in *LeaderElectionRequest, opts ...grpc.CallOption) (*LeaderElectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaderElectionResponse)
	err := c.cc.Invoke(ctx, IntersectionConsensus_LeaderElection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntersectionConsensusServer is the server API for IntersectionConsensus service.
// All implementations must embed UnimplementedIntersectionConsensusServer
// for forward compatibility.
type IntersectionConsensusServer interface {
	CandidateVote(context.Context, *CandidateVoteRequest) (*CandidateVoteResponse, error)
	LeaderElection(context.Context, *LeaderElectionRequest) (*LeaderElectionResponse, error)
	mustEmbedUnimplementedIntersectionConsensusServer()
}

// UnimplementedIntersectionConsensusServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIntersectionConsensusServer struct{}

func (UnimplementedIntersectionConsensusServer) CandidateVote(context.Context, *CandidateVoteRequest) (*CandidateVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CandidateVote not implemented")
}
func (UnimplementedIntersectionConsensusServer) LeaderElection(context.Context, *LeaderElectionRequest) (*LeaderElectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaderElection not implemented")
}
func (UnimplementedIntersectionConsensusServer) mustEmbedUnimplementedIntersectionConsensusServer() {}
func (UnimplementedIntersectionConsensusServer) testEmbeddedByValue()                               {}

// UnsafeIntersectionConsensusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntersectionConsensusServer will
// result in compilation errors.
type UnsafeIntersectionConsensusServer interface {
	mustEmbedUnimplementedIntersectionConsensusServer()
}

func RegisterIntersectionConsensusServer(s grpc.ServiceRegistrar, srv IntersectionConsensusServer) {
	// If the following call pancis, it indicates UnimplementedIntersectionConsensusServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IntersectionConsensus_ServiceDesc, srv)
}

func _IntersectionConsensus_CandidateVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CandidateVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntersectionConsensusServer).CandidateVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntersectionConsensus_CandidateVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntersectionConsensusServer).CandidateVote(ctx, req.(*CandidateVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntersectionConsensus_LeaderElection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaderElectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntersectionConsensusServer).LeaderElection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntersectionConsensus_LeaderElection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntersectionConsensusServer).LeaderElection(ctx, req.(*LeaderElectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IntersectionConsensus_ServiceDesc is the grpc.ServiceDesc for IntersectionConsensus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IntersectionConsensus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "consensus.IntersectionConsensus",
	HandlerType: (*IntersectionConsensusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CandidateVote",
			Handler:    _IntersectionConsensus_CandidateVote_Handler,
		},
		{
			MethodName: "LeaderElection",
			Handler:    _IntersectionConsensus_LeaderElection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/intersection.proto",
}
