// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: pb/intersection.proto

package consensus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoteDecision int32

const (
	VoteDecision_ACKNOWLEDGED VoteDecision = 0
	VoteDecision_IGNORED      VoteDecision = 1
)

// Enum value maps for VoteDecision.
var (
	VoteDecision_name = map[int32]string{
		0: "ACKNOWLEDGED",
		1: "IGNORED",
	}
	VoteDecision_value = map[string]int32{
		"ACKNOWLEDGED": 0,
		"IGNORED":      1,
	}
)

func (x VoteDecision) Enum() *VoteDecision {
	p := new(VoteDecision)
	*p = x
	return p
}

func (x VoteDecision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VoteDecision) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_intersection_proto_enumTypes[0].Descriptor()
}

func (VoteDecision) Type() protoreflect.EnumType {
	return &file_pb_intersection_proto_enumTypes[0]
}

func (x VoteDecision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VoteDecision.Descriptor instead.
func (VoteDecision) EnumDescriptor() ([]byte, []int) {
	return file_pb_intersection_proto_rawDescGZIP(), []int{0}
}

type ElectionStatus int32

const (
	ElectionStatus_INIT_CANDIDATE ElectionStatus = 0
	ElectionStatus_FIN_CANDIDATE  ElectionStatus = 1
	ElectionStatus_FOLLOWER       ElectionStatus = 2
	ElectionStatus_LEADER         ElectionStatus = 3
)

// Enum value maps for ElectionStatus.
var (
	ElectionStatus_name = map[int32]string{
		0: "INIT_CANDIDATE",
		1: "FIN_CANDIDATE",
		2: "FOLLOWER",
		3: "LEADER",
	}
	ElectionStatus_value = map[string]int32{
		"INIT_CANDIDATE": 0,
		"FIN_CANDIDATE":  1,
		"FOLLOWER":       2,
		"LEADER":         3,
	}
)

func (x ElectionStatus) Enum() *ElectionStatus {
	p := new(ElectionStatus)
	*p = x
	return p
}

func (x ElectionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ElectionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_intersection_proto_enumTypes[1].Descriptor()
}

func (ElectionStatus) Type() protoreflect.EnumType {
	return &file_pb_intersection_proto_enumTypes[1]
}

func (x ElectionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ElectionStatus.Descriptor instead.
func (ElectionStatus) EnumDescriptor() ([]byte, []int) {
	return file_pb_intersection_proto_rawDescGZIP(), []int{1}
}

type VehicleMeta struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`               // unique addr
	Plate          string                 `protobuf:"bytes,2,opt,name=plate,proto3" json:"plate,omitempty"`         // license plate string
	Direction      string                 `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"` // e.g., "N-left", "E-straight"
	Status         ElectionStatus         `protobuf:"varint,4,opt,name=status,proto3,enum=consensus.ElectionStatus" json:"status,omitempty"`
	SentVotes      uint32                 `protobuf:"varint,5,opt,name=sent_votes,json=sentVotes,proto3" json:"sent_votes,omitempty"`
	ReceivedVotes  uint32                 `protobuf:"varint,6,opt,name=received_votes,json=receivedVotes,proto3" json:"received_votes,omitempty"`
	ElectionTimeMs int64                  `protobuf:"varint,7,opt,name=election_time_ms,json=electionTimeMs,proto3" json:"election_time_ms,omitempty"` // last response time recorded
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VehicleMeta) Reset() {
	*x = VehicleMeta{}
	mi := &file_pb_intersection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleMeta) ProtoMessage() {}

func (x *VehicleMeta) ProtoReflect() protoreflect.Message {
	mi := &file_pb_intersection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleMeta.ProtoReflect.Descriptor instead.
func (*VehicleMeta) Descriptor() ([]byte, []int) {
	return file_pb_intersection_proto_rawDescGZIP(), []int{0}
}

func (x *VehicleMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VehicleMeta) GetPlate() string {
	if x != nil {
		return x.Plate
	}
	return ""
}

func (x *VehicleMeta) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *VehicleMeta) GetStatus() ElectionStatus {
	if x != nil {
		return x.Status
	}
	return ElectionStatus_INIT_CANDIDATE
}

func (x *VehicleMeta) GetSentVotes() uint32 {
	if x != nil {
		return x.SentVotes
	}
	return 0
}

func (x *VehicleMeta) GetReceivedVotes() uint32 {
	if x != nil {
		return x.ReceivedVotes
	}
	return 0
}

func (x *VehicleMeta) GetElectionTimeMs() int64 {
	if x != nil {
		return x.ElectionTimeMs
	}
	return 0
}

type CandidateVoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *VehicleMeta           `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandidateVoteRequest) Reset() {
	*x = CandidateVoteRequest{}
	mi := &file_pb_intersection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateVoteRequest) ProtoMessage() {}

func (x *CandidateVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_intersection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateVoteRequest.ProtoReflect.Descriptor instead.
func (*CandidateVoteRequest) Descriptor() ([]byte, []int) {
	return file_pb_intersection_proto_rawDescGZIP(), []int{1}
}

func (x *CandidateVoteRequest) GetFrom() *VehicleMeta {
	if x != nil {
		return x.From
	}
	return nil
}

type CandidateVoteResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Decision             VoteDecision           `protobuf:"varint,1,opt,name=decision,proto3,enum=consensus.VoteDecision" json:"decision,omitempty"`                           // ACKNOWLEDGED or IGNORED
	DirectionNoCollision bool                   `protobuf:"varint,2,opt,name=direction_no_collision,json=directionNoCollision,proto3" json:"direction_no_collision,omitempty"` // responder vs requester
	Responder            *VehicleMeta           `protobuf:"bytes,3,opt,name=responder,proto3" json:"responder,omitempty"`                                                      // includes responder's timing info
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CandidateVoteResponse) Reset() {
	*x = CandidateVoteResponse{}
	mi := &file_pb_intersection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateVoteResponse) ProtoMessage() {}

func (x *CandidateVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_intersection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateVoteResponse.ProtoReflect.Descriptor instead.
func (*CandidateVoteResponse) Descriptor() ([]byte, []int) {
	return file_pb_intersection_proto_rawDescGZIP(), []int{2}
}

func (x *CandidateVoteResponse) GetDecision() VoteDecision {
	if x != nil {
		return x.Decision
	}
	return VoteDecision_ACKNOWLEDGED
}

func (x *CandidateVoteResponse) GetDirectionNoCollision() bool {
	if x != nil {
		return x.DirectionNoCollision
	}
	return false
}

func (x *CandidateVoteResponse) GetResponder() *VehicleMeta {
	if x != nil {
		return x.Responder
	}
	return nil
}

type LeaderElectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FinCandidate  *VehicleMeta           `protobuf:"bytes,1,opt,name=fin_candidate,json=finCandidate,proto3" json:"fin_candidate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderElectionRequest) Reset() {
	*x = LeaderElectionRequest{}
	mi := &file_pb_intersection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderElectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderElectionRequest) ProtoMessage() {}

func (x *LeaderElectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_intersection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderElectionRequest.ProtoReflect.Descriptor instead.
func (*LeaderElectionRequest) Descriptor() ([]byte, []int) {
	return file_pb_intersection_proto_rawDescGZIP(), []int{3}
}

func (x *LeaderElectionRequest) GetFinCandidate() *VehicleMeta {
	if x != nil {
		return x.FinCandidate
	}
	return nil
}

type LeaderElectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      VoteDecision           `protobuf:"varint,1,opt,name=decision,proto3,enum=consensus.VoteDecision" json:"decision,omitempty"` // ACKNOWLEDGED or IGNORED
	Responder     *VehicleMeta           `protobuf:"bytes,2,opt,name=responder,proto3" json:"responder,omitempty"`                            // includes responder's timing info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderElectionResponse) Reset() {
	*x = LeaderElectionResponse{}
	mi := &file_pb_intersection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderElectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderElectionResponse) ProtoMessage() {}

func (x *LeaderElectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_intersection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderElectionResponse.ProtoReflect.Descriptor instead.
func (*LeaderElectionResponse) Descriptor() ([]byte, []int) {
	return file_pb_intersection_proto_rawDescGZIP(), []int{4}
}

func (x *LeaderElectionResponse) GetDecision() VoteDecision {
	if x != nil {
		return x.Decision
	}
	return VoteDecision_ACKNOWLEDGED
}

func (x *LeaderElectionResponse) GetResponder() *VehicleMeta {
	if x != nil {
		return x.Responder
	}
	return nil
}

var File_pb_intersection_proto protoreflect.FileDescriptor

const file_pb_intersection_proto_rawDesc = "" +
	"\n" +
	"\x15pb/intersection.proto\x12\tconsensus\"\xf4\x01\n" +
	"\vVehicleMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05plate\x18\x02 \x01(\tR\x05plate\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\tR\tdirection\x121\n" +
	"\x06status\x18\x04 \x01(\x0e2\x19.consensus.ElectionStatusR\x06status\x12\x1d\n" +
	"\n" +
	"sent_votes\x18\x05 \x01(\rR\tsentVotes\x12%\n" +
	"\x0ereceived_votes\x18\x06 \x01(\rR\rreceivedVotes\x12(\n" +
	"\x10election_time_ms\x18\a \x01(\x03R\x0eelectionTimeMs\"B\n" +
	"\x14CandidateVoteRequest\x12*\n" +
	"\x04from\x18\x01 \x01(\v2\x16.consensus.VehicleMetaR\x04from\"\xb8\x01\n" +
	"\x15CandidateVoteResponse\x123\n" +
	"\bdecision\x18\x01 \x01(\x0e2\x17.consensus.VoteDecisionR\bdecision\x124\n" +
	"\x16direction_no_collision\x18\x02 \x01(\bR\x14directionNoCollision\x124\n" +
	"\tresponder\x18\x03 \x01(\v2\x16.consensus.VehicleMetaR\tresponder\"T\n" +
	"\x15LeaderElectionRequest\x12;\n" +
	"\rfin_candidate\x18\x01 \x01(\v2\x16.consensus.VehicleMetaR\ffinCandidate\"\x83\x01\n" +
	"\x16LeaderElectionResponse\x123\n" +
	"\bdecision\x18\x01 \x01(\x0e2\x17.consensus.VoteDecisionR\bdecision\x124\n" +
	"\tresponder\x18\x02 \x01(\v2\x16.consensus.VehicleMetaR\tresponder*-\n" +
	"\fVoteDecision\x12\x10\n" +
	"\fACKNOWLEDGED\x10\x00\x12\v\n" +
	"\aIGNORED\x10\x01*Q\n" +
	"\x0eElectionStatus\x12\x12\n" +
	"\x0eINIT_CANDIDATE\x10\x00\x12\x11\n" +
	"\rFIN_CANDIDATE\x10\x01\x12\f\n" +
	"\bFOLLOWER\x10\x02\x12\n" +
	"\n" +
	"\x06LEADER\x10\x032\xc2\x01\n" +
	"\x15IntersectionConsensus\x12R\n" +
	"\rCandidateVote\x12\x1f.consensus.CandidateVoteRequest\x1a .consensus.CandidateVoteResponse\x12U\n" +
	"\x0eLeaderElection\x12 .consensus.LeaderElectionRequest\x1a!.consensus.LeaderElectionResponseBEZCgithub.com/ymalegao/DistributedSystemsforAVs/pb/consensus;consensusb\x06proto3"

var (
	file_pb_intersection_proto_rawDescOnce sync.Once
	file_pb_intersection_proto_rawDescData []byte
)

func file_pb_intersection_proto_rawDescGZIP() []byte {
	file_pb_intersection_proto_rawDescOnce.Do(func() {
		file_pb_intersection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_intersection_proto_rawDesc), len(file_pb_intersection_proto_rawDesc)))
	})
	return file_pb_intersection_proto_rawDescData
}

var file_pb_intersection_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pb_intersection_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_intersection_proto_goTypes = []any{
	(VoteDecision)(0),              // 0: consensus.VoteDecision
	(ElectionStatus)(0),            // 1: consensus.ElectionStatus
	(*VehicleMeta)(nil),            // 2: consensus.VehicleMeta
	(*CandidateVoteRequest)(nil),   // 3: consensus.CandidateVoteRequest
	(*CandidateVoteResponse)(nil),  // 4: consensus.CandidateVoteResponse
	(*LeaderElectionRequest)(nil),  // 5: consensus.LeaderElectionRequest
	(*LeaderElectionResponse)(nil), // 6: consensus.LeaderElectionResponse
}
var file_pb_intersection_proto_depIdxs = []int32{
	1, // 0: consensus.VehicleMeta.status:type_name -> consensus.ElectionStatus
	2, // 1: consensus.CandidateVoteRequest.from:type_name -> consensus.VehicleMeta
	0, // 2: consensus.CandidateVoteResponse.decision:type_name -> consensus.VoteDecision
	2, // 3: consensus.CandidateVoteResponse.responder:type_name -> consensus.VehicleMeta
	2, // 4: consensus.LeaderElectionRequest.fin_candidate:type_name -> consensus.VehicleMeta
	0, // 5: consensus.LeaderElectionResponse.decision:type_name -> consensus.VoteDecision
	2, // 6: consensus.LeaderElectionResponse.responder:type_name -> consensus.VehicleMeta
	3, // 7: consensus.IntersectionConsensus.CandidateVote:input_type -> consensus.CandidateVoteRequest
	5, // 8: consensus.IntersectionConsensus.LeaderElection:input_type -> consensus.LeaderElectionRequest
	4, // 9: consensus.IntersectionConsensus.CandidateVote:output_type -> consensus.CandidateVoteResponse
	6, // 10: consensus.IntersectionConsensus.LeaderElection:output_type -> consensus.LeaderElectionResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_pb_intersection_proto_init() }
func file_pb_intersection_proto_init() {
	if File_pb_intersection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_intersection_proto_rawDesc), len(file_pb_intersection_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_intersection_proto_goTypes,
		DependencyIndexes: file_pb_intersection_proto_depIdxs,
		EnumInfos:         file_pb_intersection_proto_enumTypes,
		MessageInfos:      file_pb_intersection_proto_msgTypes,
	}.Build()
	File_pb_intersection_proto = out.File
	file_pb_intersection_proto_goTypes = nil
	file_pb_intersection_proto_depIdxs = nil
}
